language: vim

cache:
  directories:
    - $HOME/.vvm

before_install:
  - curl https://raw.githubusercontent.com/kana/vim-version-manager/master/bin/vvm | python - setup; true
  - source ~/.vvm/etc/login
  - vvm update_itself
  - vvm use vimorg--v8.2.0717 --install --with-features=huge

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  vim -Es -Nu tests/vimrc -c "set rtp+=vader.vim" -c "runtime plugin/vader.vim" -c "Vader! tests/*" > /dev/null
