name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
test:
    name: Test on Neovim ${{ matrix.neovim }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [false, true]
        version: ['stable', 'nightly']

    steps:
    - uses: actions/checkout@v2
    - name: Use Neovim? ${{ matrix.neovim }}
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: ${{ matrix.neovim }}
        version: ${{ matrix.version }}
    
    - name: Run tests
      uses: PsychoLlama/vader-action@v1
      with:
        neovim: ${{ matrix.neovim }}
