name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        version: stable
        neovim: true

    - uses: actions/checkout@v2
      with:
        repository: junegunn/vader.vim
        path: vader.vim
    - name: Run tests
      run: nvim -Es -Nu tests/vimrc -c "set rtp+=vader.vim" -c "Vader! tests/*" > /dev/null

