name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: ["stable", "nightly"]
        name: ["Vim", "Neovim"]
        include:
          - name: "Vim"
            neovim: false
            exe: "vim"
          - name: "Neovim"
            neovim: true
            exe: "nvim"

    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.name }}
      uses: rhysd/action-setup-vim@v1
      with:
        version: ${{ matrix.version }}
        neovim: ${{ matrix.neovim }}

    - uses: actions/checkout@v2
      with:
        repository: junegunn/vader.vim
        path: vader.vim
    - name: Run tests
      env:
        EXE: ${{ matrix.exe }}
      run: ${EXE} -Es -Nu tests/vimrc -c "Vader! tests/*" > /dev/null

